### ISSUE TITLE
Quick Questions

### ISSUE THREAD

**Issue by SCasarotto** [tanem/media-query-facade#19]
Hey @tanem I started checking out some of your other repos and was reading this one. I didn't know JS could access media queries. This seems really cool. There have been a few times where something like this would have been really useful. 

Where have you seen soemthing like this implemented? 
What problems have you seen this solve that doing via CSS would be significantly worse?

Feel free to close anytime.

**Comment by tanem** [comment]
Hey @SCasarotto.

Hmm this is quite an old module, but IIRC the motivation was we were working on a website that had some JS components written with [Marionette](https://marionettejs.com/), and we wanted to render them differently when certain breakpoints were active (i.e. make more complex layout changes than could be achieved with CSS breakpoints alone).

We were using CSS breakpoints as well, and it was fairly common for the JS component layout changes to occur in tandem with CSS changes occurring on other parts of the page for a certain media query. So it was nice to be able to match those up when needed.
 
To answer your questions:

> Where have you seen something like this implemented?

At the time this module was written there were other approaches around that were utilising `window.matchMedia`, but we were wanting a specific API.

> What problems have you seen this solve that doing via CSS would be significantly worse?

As described above, this module was designed to address things we just couldn't do at the time with CSS alone. The world's changed a lot since then though, so I'm sure there will be more options to choose from now to address that same use-case 😄

**Comment by SCasarotto** [comment]
Very cool. Thanks!
